service: mvps-printing

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
    TWOFACTOR_API_KEY:  ${env:TWOFACTOR_API_KEY}
    EMAIL_USER:         ${env:EMAIL_USER}
    EMAIL_PASS:         ${env:EMAIL_PASS}
    DB_HOST:            ${env:DB_HOST}
    DB_PORT:            ${env:DB_PORT}
    DB_USER:            ${env:DB_USER}
    DB_PASS:            ${env:DB_PASS}
    DB_NAME:            ${env:DB_NAME}

package:
  excludeDevDependencies: true
  include:
    - package.json

custom:
  dotenv:
    required: true
    include:
      - AWS_S3_BUCKET_NAME
      - TWOFACTOR_API_KEY
      - EMAIL_USER
      - EMAIL_PASS
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME

  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
    format: cjs
    external:
      - aws-sdk
      - sqlite3
      - sqlite
      - react
      - react-dom
      - react-hot-toast
      - react-icons
      - react-qr-code
      - pdf-lib
      - pdfjs-dist
      - firebase
    concurrency: 10

functions:
  api:
    handler: handler.main
    events:
      - httpApi: "*"
